### PR TITLE
minor edits and tweaks

### PR DESCRIPTION
**Pull request by kbarbary**
- better sloan logo for white background
- Sep 1 end date
- comment out "apply" button for now
- YouTube playlist for 2016 lecture videos

### CODE REVIEW

**Comment by kbarbary** [comment]
Also, I recommend we delete the `master` branch in this repo... it only causes confusion.

**Comment by kbarbary** [comment]
I also commented out the "tell me more" button because it displayed weirdly on my browser and seemed unnecessary:

image

**Comment by dhuppenkothen** [comment]
Looks good to me! Merging.

**Comment by dhuppenkothen** [comment]
Forgot to say: thanks for making these edits! :)

**Pull request merged**
